export const APP_STRINGS = {
  app: {
    name: 'SisteContact',
    subtitle: 'Prospectador',
    tagline: 'Busca comercios por tipo y zona',
  },
  tabs: {
    search: 'Buscar',
    prospects: 'Prospectos',
    visits: 'Visitas',
    visited: 'Visitados',
  },
  home: {
    title: 'SisteContact',
    subtitle: 'Busca comercios por tipo y zona',
    description: 'Selecciona una zona, ajusta el radio y encuentra negocios cercanos.',
  },
  login: {
    subtitle: 'Inicia sesión para continuar',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu@correo.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    submit: 'Entrar',
    submitting: 'Entrando...',
    checkingSession: 'Comprobando sesión...',
    emailRequired: 'Ingresa tu correo.',
    passwordRequired: 'Ingresa tu contraseña.',
    noRegisterHint:
      'No hay registro público. Si no tienes acceso, contacta al administrador.',
    logout: 'Cerrar sesión',
    errors: {
      invalidEmail: 'El correo no es válido.',
      userDisabled: 'Esta cuenta está deshabilitada.',
      invalidCredential: 'Correo o contraseña incorrectos.',
      tooManyRequests: 'Demasiados intentos. Espera un momento e inténtalo de nuevo.',
      network: 'Error de red. Revisa tu conexión.',
      generic: 'No se pudo iniciar sesión. Inténtalo de nuevo.',
    },
  },
  search: {
    title: 'Buscar comercios',
    typeLabel: 'Tipo de comercio',
    typePlaceholder: 'Ej: barberías, panaderías, ferreterías...',
    zoneLabel: 'Zona',
    zonePlaceholder: 'Escribe un sector o barrio...',
    zoneHint: 'Selecciona una zona de la lista',
    radiusLabel: 'Radio de búsqueda',
    radiusValue: (km: number) =>
      km === 1 ? '1 km a la redonda' : `${km} km a la redonda`,
    mapToggleLabel: 'Mapa',
    mapToggleOn: 'Mostrar mapa',
    mapToggleOff: 'Ocultar mapa',
    submit: 'Buscar',
    loading: 'Buscando...',
    noResults: 'No se encontraron comercios en esta zona.',
    resultsTitle: (count: number, type: string, zone: string, radiusKm?: number) => {
      const area =
        radiusKm && radiusKm > 0
          ? `${zone} (${radiusKm} km)`
          : zone
      return `${count} ${count === 1 ? 'comercio' : 'comercios'} de "${type}" en ${area}`
    },
    errorGeneric: 'Ocurrió un error. Inténtalo de nuevo.',
    zoneRequired: 'Primero selecciona una zona.',
    typeRequired: 'Escribe el tipo de comercio.',
  },
  prospects: {
    title: 'Prospectos',
    subtitle:
      'Define el estado de contacto de cada comercio (contactado, no le interesa, servicio activo).',
    empty:
      'Aún no tienes prospectos. Agrégalos desde los resultados de búsqueda.',
    loading: 'Cargando prospectos...',
    error: 'No se pudo cargar la lista de prospectos',
    remove: 'Quitar de prospectos',
    filterAll: 'Todos',
    filterEmpty: 'No hay comercios con ese estado.',
  },
  visits: {
    title: 'Visitas',
    subtitle: 'Agenda visitas y registra el resultado de cada una.',
    empty:
      'No hay prospectos para agendar. Primero agrégalos desde Buscar o Prospectos.',
    loading: 'Cargando visitas...',
    error: 'No se pudo cargar la agenda de visitas',
    filterDateEmpty: 'No hay visitas pendientes para esa fecha.',
    filterDateAll: 'Todas las fechas',
    filterDateToday: 'Hoy',
    filterDateTomorrow: 'Mañana',
    filterDateCustom: 'Fecha',
    filterDateCustomLabel: 'Elegir fecha',
    sectionToday: 'Hoy',
    sectionOverdue: 'Atrasados',
    sectionUpcoming: 'Próximos días',
    sectionNoDate: 'Sin visita agendada',
    visitDateLabel: 'Agendar visita',
    noVisitDate: 'Sin fecha asignada',
    saveDate: 'Guardar agenda',
    clearDate: 'Quitar agenda',
  },
  visited: {
    title: 'Comercios visitados',
    subtitle: 'Histórico de tus visitas y notas.',
    empty: 'Aún no has marcado comercios como visitados.',
    loading: 'Cargando visitados...',
    error: 'No se pudo cargar los visitados',
  },
  export: {
    xlsx: 'Exportar Excel',
  },
  business: {
    openNow: 'Abierto ahora',
    closed: 'Cerrado',
    reviews: (n: number) => `${n} reseñas`,
    reviewsLabel: 'Reseñas',
    viewOnMaps: 'Ver en Google Maps',
    noRating: 'Sin valoraciones',
    phone: 'Teléfono',
    noPhone: 'Sin teléfono',
    visitedBadge: 'Visitado',
    prospectBadge: 'Prospecto',
    markVisited: 'Marcar como visitado',
    editVisit: 'Editar visita',
    unmarkVisited: 'Quitar visitado',
    addProspect: 'Agregar a prospectos',
    removeProspect: 'Quitar de prospectos',
    notesLabel: 'Notas de la visita',
    notesPlaceholder: 'Anota qué observaste, a quién hablaste, etc.',
    resultLabel: 'Resultado de la visita',
    resultPlaceholder: 'Ej: interesado, no disponible, agendar seguimiento...',
    saveVisit: 'Guardar visita',
    savingVisit: 'Guardando...',
    visitSaved: 'Visita guardada',
    visitError: 'No se pudo guardar la visita',
    prospectError: 'No se pudo actualizar el prospecto',
    visitDateLabel: '¿Qué día planeas visitarlo?',
    visitDateRequired: 'Elige una fecha de visita.',
    statusError: 'No se pudo actualizar el estado de contacto',
    whoVisited: 'Citas y visitas',
    whoVisitedTitle: 'Visitantes de este comercio',
    whoVisitedEmpty: 'Nadie ha marcado este comercio como visitado aún.',
    whoVisitedLoading: 'Cargando visitantes...',
    whoVisitedError: 'No se pudieron cargar los visitantes',
    whoVisitedResult: 'Resultado',
    whoScheduled: 'Citas programadas',
    whoScheduledTitle: 'Citas programadas en este comercio',
    whoScheduledEmpty: 'Nadie tiene una cita programada aquí aún.',
    whoScheduledLoading: 'Cargando citas...',
    whoScheduledError: 'No se pudieron cargar las citas programadas',
    whoScheduledDate: 'Fecha',
    youLabel: 'Tú',
  },
} as const

export type AppStrings = typeof APP_STRINGS
