export const APP_STRINGS = {
  app: {
    name: 'SisteContact',
    subtitle: 'Prospectador',
    tagline: 'Busca comercios por tipo y zona',
  },
  tabs: {
    search: 'Buscar',
    prospects: 'Prospectos',
    visits: 'Por Contactar',
    contacted: 'Contactados',
  },
  scheduling: {
    intervalLabel: 'Intervalo entre citas',
    intervalHint:
      'Las horas de visita usan este intervalo y no se permiten citas más cercanas.',
    intervalOption: (mins: number) => `${mins} minutos`,
    saving: 'Guardando...',
    saved: 'Guardado',
    loadError: 'No se pudo cargar el intervalo de citas',
    saveError: 'No se pudo guardar el intervalo de citas',
  },
  home: {
    title: 'SisteContact',
    subtitle: 'Busca comercios por tipo y zona',
    description: 'Selecciona una zona, ajusta el radio y encuentra negocios cercanos.',
  },
  profile: {
    button: 'Mi perfil',
    title: 'Mi perfil',
    close: 'Cerrar',
    loading: 'Cargando estadísticas...',
    error: 'No se pudieron cargar las estadísticas',
    kpiProspects: 'Prospectos',
    kpiContacted: 'Contactados',
    kpiClosedSales: 'Ventas cerradas',
    kpiVisits: 'Visitas',
    chartContactStatus: 'Estado de contacto en prospectos',
    chartContactOutcomes: 'Clasificación de contactos (llamada)',
    chartVisitOutcomes: 'Resultado de visitas',
    emptyProspects: 'Aún no tienes prospectos agregados.',
    emptyOutcomes: 'Aún no hay contactos clasificados.',
    emptyVisits: 'Aún no hay visitas con resultado registrado.',
    calendarTitle: 'Google Calendar',
    calendarSubtitle:
      'Conecta tu cuenta para recibir recordatorios de llamadas y visitas agendadas.',
    calendarConnected: 'Conectado',
    calendarDisconnected: 'No conectado',
    calendarNotConfigured:
      'Google Calendar aún no está habilitado en el servidor. Configura las credenciales OAuth.',
    calendarConnect: 'Conectar Google Calendar',
    calendarDisconnect: 'Desconectar',
    calendarConnecting: 'Redirigiendo...',
    calendarDisconnecting: 'Desconectando...',
    calendarLoadError: 'No se pudo cargar el estado de Google Calendar',
    calendarConnectError: 'No se pudo iniciar la conexión con Google Calendar',
    calendarDisconnectError: 'No se pudo desconectar Google Calendar',
    calendarConnectedFlash: 'Google Calendar conectado correctamente.',
    calendarErrorFlash: 'No se pudo completar la conexión con Google Calendar.',
  },
  login: {
    subtitle: 'Inicia sesión para continuar',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu@correo.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    submit: 'Entrar',
    submitting: 'Entrando...',
    checkingSession: 'Comprobando sesión...',
    emailRequired: 'Ingresa tu correo.',
    passwordRequired: 'Ingresa tu contraseña.',
    noRegisterHint:
      'No hay registro público. Si no tienes acceso, contacta al administrador.',
    logout: 'Cerrar sesión',
    errors: {
      invalidEmail: 'El correo no es válido.',
      userDisabled: 'Esta cuenta está deshabilitada.',
      invalidCredential: 'Correo o contraseña incorrectos.',
      tooManyRequests: 'Demasiados intentos. Espera un momento e inténtalo de nuevo.',
      network: 'Error de red. Revisa tu conexión.',
      generic: 'No se pudo iniciar sesión. Inténtalo de nuevo.',
    },
  },
  search: {
    title: 'Buscar comercios',
    typeLabel: 'Tipo de comercio',
    typePlaceholder: 'Ej: barberías, panaderías, ferreterías...',
    zoneLabel: 'Zona',
    zonePlaceholder: 'Escribe un sector o barrio...',
    zoneHint: 'Selecciona una zona de la lista',
    radiusLabel: 'Radio de búsqueda',
    radiusValue: (km: number) =>
      km === 1 ? '1 km a la redonda' : `${km} km a la redonda`,
    mapToggleLabel: 'Mapa',
    mapToggleOn: 'Mostrar mapa',
    mapToggleOff: 'Ocultar mapa',
    submit: 'Buscar',
    loading: 'Buscando...',
    noResults: 'No se encontraron comercios en esta zona.',
    resultsTitle: (count: number, type: string, zone: string, radiusKm?: number) => {
      const area =
        radiusKm && radiusKm > 0
          ? `${zone} (${radiusKm} km)`
          : zone
      return `${count} ${count === 1 ? 'comercio' : 'comercios'} de "${type}" en ${area}`
    },
    errorGeneric: 'Ocurrió un error. Inténtalo de nuevo.',
    zoneRequired: 'Primero selecciona una zona.',
    typeRequired: 'Escribe el tipo de comercio.',
  },
  prospects: {
    title: 'Prospectos',
    subtitle:
      'Estado de contacto, agenda de llamada o visita y seguimiento de cada comercio.',
    empty:
      'Aún no tienes prospectos. Agrégalos desde los resultados de búsqueda.',
    loading: 'Cargando prospectos...',
    error: 'No se pudo cargar la lista de prospectos',
    remove: 'Quitar de prospectos',
    filterAll: 'Todos',
    filterEmpty: 'No hay comercios con ese estado.',
    outcomeRequired: 'Elige una clasificación del contacto.',
    notesLabel: 'Anotaciones del contacto',
    notesPlaceholder: 'Qué se habló, con quién, próximos pasos...',
    outcomeLabel: 'Clasificación',
    saveContact: 'Guardar contacto',
    visitDateLabel: 'Agendar visita',
    noVisitDate: 'Sin fecha de visita',
    visitTimeLabel: 'Hora',
    visitTimePlaceholder: 'Elige hora',
    visitTimeRequired: 'Elige una hora de visita.',
    callDateLabel: 'Agendar llamada',
    noCallDate: 'Sin fecha de llamada',
    callTimeLabel: 'Hora',
    callTimePlaceholder: 'Elige hora',
    saveDate: 'Guardar agenda',
    clearDate: 'Quitar agenda',
    callDateRequired: 'Elige una fecha de llamada.',
    callTimeRequired: 'Elige una hora de llamada.',
    scheduledLabel: 'Agendado',
    badgeCall: 'Llamada',
    badgeVisit: 'Visita',
  },
  visits: {
    title: 'Por Contactar',
    subtitle:
      'Llamadas y visitas agendadas. Contacta y registra el resultado.',
    empty:
      'No hay citas agendadas. Agenda una llamada o visita desde Prospectos.',
    loading: 'Cargando agenda...',
    error: 'No se pudo cargar la agenda',
    filterDateEmpty: 'No hay citas pendientes para esa fecha.',
    filterDateAll: 'Todas las fechas',
    filterDateToday: 'Hoy',
    filterDateTomorrow: 'Mañana',
    filterDateCustom: 'Fecha',
    filterDateCustomLabel: 'Elegir fecha',
    sectionToday: 'Hoy',
    sectionOverdue: 'Atrasados',
    sectionUpcoming: 'Próximos días',
    sectionNoDate: 'Sin cita agendada',
    visitDateLabel: 'Agendar visita',
    noVisitDate: 'Sin fecha de visita',
    visitTimeLabel: 'Hora',
    visitTimePlaceholder: 'Elige hora',
    callDateLabel: 'Agendar llamada',
    noCallDate: 'Sin fecha de llamada',
    callTimeLabel: 'Hora',
    callTimePlaceholder: 'Elige hora',
    saveDate: 'Guardar agenda',
    clearDate: 'Quitar agenda',
    badgeCall: 'Llamada',
    badgeVisit: 'Visita',
    tabAll: 'Todos',
    tabVisit: 'Visitar',
    tabCall: 'Llamar',
    emptyVisit:
      'No hay visitas agendadas. Agenda una desde Prospectos.',
    emptyCall:
      'No hay llamadas agendadas. Agenda una desde Prospectos.',
    filterChannelEmpty: 'No hay citas en esta pestaña para esa fecha.',
    expandCard: 'Ver detalle',
    collapseCard: 'Ocultar detalle',
    scheduledLabel: 'Agendado',
    unscheduledLabel: 'Sin agenda',
  },
  contacted: {
    title: 'Comercios contactados',
    subtitle: 'Contactos por llamada y visitas presenciales.',
    empty: 'Aún no has contactado comercios por llamada ni visita.',
    loading: 'Cargando contactados...',
    error: 'No se pudo cargar los contactados',
    channelCall: 'Llamada',
    channelVisit: 'Visita',
  },
  export: {
    xlsx: 'Exportar Excel',
    pdf: 'Exportar PDF',
  },
  business: {
    openNow: 'Abierto ahora',
    closed: 'Cerrado',
    reviews: (n: number) => `${n} reseñas`,
    reviewsLabel: 'Reseñas',
    viewOnMaps: 'Ver en Google Maps',
    noRating: 'Sin valoraciones',
    phone: 'Teléfono',
    noPhone: 'Sin teléfono',
    visitedBadge: 'Visitado',
    prospectBadge: 'Prospecto',
    markVisited: 'Marcar como visitado',
    editVisit: 'Editar visita',
    unmarkVisited: 'Quitar visitado',
    addProspect: 'Agregar a prospectos',
    removeProspect: 'Quitar de prospectos',
    notesLabel: 'Notas de la visita',
    notesPlaceholder: 'Anota qué observaste, a quién hablaste, etc.',
    resultLabel: 'Resultado final de la visita',
    resultRequired: 'Elige el resultado final de la visita.',
    saveVisit: 'Guardar visita',
    savingVisit: 'Guardando...',
    visitSaved: 'Visita guardada',
    visitError: 'No se pudo guardar la visita',
    prospectError: 'No se pudo actualizar el prospecto',
    visitDateLabel: '¿Qué día planeas visitarlo?',
    visitDateRequired: 'Elige una fecha de visita.',
    statusError: 'No se pudo actualizar el estado de contacto',
    whoVisited: 'Citas y visitas',
    whoVisitedTitle: 'Visitantes de este comercio',
    whoVisitedEmpty: 'Nadie ha marcado este comercio como visitado aún.',
    whoVisitedLoading: 'Cargando visitantes...',
    whoVisitedError: 'No se pudieron cargar los visitantes',
    whoVisitedResult: 'Resultado',
    whoScheduled: 'Citas programadas',
    whoScheduledTitle: 'Citas programadas en este comercio',
    whoScheduledEmpty: 'Nadie tiene una cita programada aquí aún.',
    whoScheduledLoading: 'Cargando citas...',
    whoScheduledError: 'No se pudieron cargar las citas programadas',
    whoScheduledDate: 'Fecha',
    youLabel: 'Tú',
  },
} as const

export type AppStrings = typeof APP_STRINGS
